### ISSUE TITLE
[SUGGESTION] Add AMD iGPU support with NootedRed

### ISSUE THREAD

**Issue by raphipod** [Coopydood/ultimate-macOS-KVM#107]
### Describe the Suggestion

Make it possible to passthrough the AMD CPU's iGPU to the macOS KVM using NootedRed, which offers support for many AMD iGPU's.

### Suggestion Type

- [X] New Feature
- [ ] Related to an existing feature
- [ ] Other

### Concept Images

![grafik](https://github.com/user-attachments/assets/0a8535bb-abd3-4193-a555-e5c0ee023bd2)
(taken off Reddit from u/Blackpilot9, just used as an example to show that it works)

### Additional Information

NootedRed is a macOS Kernel Extension (kext) for Lilu 1.6.4+, which enables recent AMD iGPU's for 10.15 up to and (probably) not limited to macOS 14.

More information on https://chefkissinc.github.io/nootedred

**Comment by Coopydood** [comment]
I am interested in adding iGPU support in general, both intel and AMD. I don't have an AMD CPU to test though, so I'd need some kind of evidence that it works specifically with KVM / VMs; and the method used to pass through the iGPU

Many thanks
