### ISSUE TITLE
 No boot with resizable BAR on - AMD RX 580

### ISSUE THREAD

**Issue by tuxrinku** [Coopydood/ultimate-macOS-KVM#113]
My hackintosh with a RX 580 passthrough doesn't boot when resizable bar is enabled in BIOS. There's no problem at all when it's disabled. I tried to set ResizeAppleGpuBar to 0 in config.plist as mentioned in the OpenCore documentation but it doesn't change anything. I'd like to enable it since my main gpu gets a few extra fps when ReBAR is on.

My guess is that since the RX 580 doesn't support ReBAR, the hackintosh machine won't boot when it's enabled. So ideally there would be a way to enable it for my Nvidia card, and disable it for the AMD one.

Any suggestion ?

**Comment by Coopydood** [comment]
Hi

Resizeable BAR is known to cause major issues with virtualisation. 

The recommendation is to leave it off. 

Thanks
