### ISSUE TITLE
[ULTMOS] GenSMBIOS.py: Permission denied

### ISSUE THREAD

**Issue by bonnjalal** [Coopydood/ultimate-macOS-KVM#126]
### Describe the Issue

When I try to Generate a new serial number using **5. Generate SMBIOS / Serial Number...** option from main.py script I get this error even when I use it with root access.
`sh: line 1: ./resources/python/smbios/GenSMBIOS.py: Permission denied`

But when I try to run the GenSMBIOS.py by itself it works just fine.

### Operating System

NixOS

### Kernel

6.1.111

### Processor

Intel i7-4800MQ

### RAM (in GB)

22GB

### GPU(s)

NVIDIA Quadro K2100M, Intel 4th Gen Core Processor

### Version

v0.12.4

### Branch

main

**Comment by Coopydood** [comment]
What permissions does the file have?

Does it definitely have `+x`?
