### ISSUE TITLE
[macOS] 

### ISSUE THREAD

**Issue by NanoNM** [Coopydood/ultimate-macOS-KVM#128]
### Describe the Issue

x79 plantform without AVX2 can not boot Ventura

### Reproduce the Issue

![截图 2024-10-06 16-10-12](https://github.com/user-attachments/assets/6fa20921-3f1b-449d-a18d-2f3118d92cdb)

### Operating System

Linux xxx 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Kernel

Linux 6.8.0-45-generic

### Processor

Intel® Xeon® E5-2660 0 × 16

### RAM (in GB)

16

### GPU(s)

16

### Version

0.12.4

### Branch

main

**Comment by Coopydood** [comment]
Hi,

I'll need more info. 
Can you send the relevant AutoPilot log? (<repo>/logs)

It would also help if you sent a system profiler. You can run it through `Main menu > Compatibility checks > System profiler`

Thanks
