### ISSUE TITLE
You are not connected to the internet

### ISSUE THREAD

**Issue by M3nti0nL3Ss** [Coopydood/ultimate-macOS-KVM#14]
My internet connection is fine, but Ventura can't access it trough qemu.
I use Arch BTW.

![Screenshot_20230803_205104](https://github.com/Coopydood/ultimate-macOS-KVM/assets/30575106/cf6d24c4-e101-4224-950d-88ce83e98176)

**Comment by Coopydood** [comment]
What network adapter model was chosen?

**Comment by M3nti0nL3Ss** [comment]
I have tried foxlet's project and it worked.
The chosen adapter öodel was e1000-82545em, the same as foxlet's project.

**Comment by Coopydood** [comment]
> I have tried foxlet's project and it worked.
> 
> The chosen adapter öodel was e1000-82545em, the same as foxlet's project.

Okay, try changing it to `vmxnet3`

**Comment by M3nti0nL3Ss** [comment]
It worked.
Thank you for this awesome project :D

**Comment by Coopydood** [comment]
No problem! Out of curiosity, did you manually change the adapter through AutoPilot's custom value option, or was it the "default"?

And thanks for the kind words, means a lot!

**Comment by M3nti0nL3Ss** [comment]
The e1000-82545em adapter was the default value on Autopilot, and then I changed it on boot.sh file and it worked.

**Comment by Coopydood** [comment]
> The e1000-82545em adapter was the default value on Autopilot, and then I changed it on boot.sh file and it worked.

Interesting. What was your target OS set to on autopilot?

**Comment by M3nti0nL3Ss** [comment]
It was the last option, Ventura.

**Comment by Coopydood** [comment]
> It was the last option, Ventura.

On this stage?

![image](https://github.com/Coopydood/ultimate-macOS-KVM/assets/39441479/a04ed7e3-3bb5-4d6f-afa4-46bf893a7846)
