### ISSUE TITLE
How to edit boot arguments? 

### ISSUE THREAD

**Issue by MichaelDevon** [Coopydood/ultimate-macOS-KVM#143]
### Describe the Suggestion

In the troubleshooting section i read that i need NOT to pass the `-v` argument during boot to avoid it hanging on PCIE stuff. It happens even before the OS is installed so i have no idea how to pass the argument now before its even installed.

After the documentation says i need to do this, it could tell the methodology as well. 

### Suggestion Type

- [ ] New Feature
- [ ] Related to an existing feature
- [ ] Other

**Comment by KitsuneBalloon** [comment]
Hi there!

You can edit boot arguments by going to Extras --> 3. macOS Boot Arguments.
