### ISSUE TITLE
[SUGGESTION] Automatically add VMHide.kext if user selects Sequoia

### ISSUE THREAD

**Issue by xdien** [Coopydood/ultimate-macOS-KVM#146]
### Describe the Suggestion

I had a problem with last version `sequoia`, apple blocked vm users from logging into icloud account, I solved it by adding https://github.com/Carnations-Botanica/VMHide . I think many people will have the same problem as me 

### Suggestion Type

- [X] New Feature
- [ ] Related to an existing feature
- [ ] Other

**Comment by KitsuneBalloon** [comment]
Hi there. There is no need to add this.

We already have a patched opencore image that aims to fix iCloud issues on Sequoia.

It can be found here: https://github.com/Coopydood/ultimate-macOS-KVM/tree/iCloudPatch

Download the OpenCore.qcow2 file there and replace your current one.

But please do **REMEMBER TO BACKUP YOUR OC DIRECTORY BEFORE PROCEEDING**

**Comment by Coopydood** [comment]
Side note, the iCloudPatch branch is now deprecated, please use the dev branch as it has the merged changes. 

Thanks
