### ISSUE TITLE
AutoPilot wiki page does not explain required string values

### ISSUE THREAD

**Issue by eversiege** [Coopydood/ultimate-macOS-KVM#15]
I must give a bit of clarification on this. Even though on the table it's shown in bold required suffixes, it is not explained anywhere on the wiki that it is required.

I cannot push to wiki directly, but if you need to directly show user a little note or a warning use the `> Note:` syntax for GitHub Markdown.

**Comment by Coopydood** [comment]
Wiki has been updated with a key note.
