### ISSUE TITLE
virt-manager Error connecting to graphical console

### ISSUE THREAD

**Issue by ada012** [Coopydood/ultimate-macOS-KVM#36]
But when I use virt-manager to import the boot .xml file:

```
Error connecting to graphical console: The client is on a remote host, but is configured to allow local file descriptor connections only.
```

Where should I go to set up to provide support for remote access

**Comment by Coopydood** [comment]
> But when I use virt-manager to import the boot .xml file:
> 
> ```
> Error connecting to graphical console: The client is on a remote host, but is configured to allow local file descriptor connections only.
> ```
> 
> Where should I go to set up to provide support for remote access

Hi, can you please send your .sh file, .xml file, and if possible, your autopilot log stored in [repo folder]/logs

Many thanks
