### ISSUE TITLE
[SUGGESTION] Change HDD.qcow2 disk type to qcow2 instead of raw

### ISSUE THREAD

**Issue by User8395** [Coopydood/ultimate-macOS-KVM#42]
> [!NOTE]
> This should be used only to submit **suggestions**, NOT issues and bugs.

## Suggestion
Please describe your suggestion for **ultimate-macOS-KVM**.

Because the HDD.qcow2 type is set to raw, the VM sees the size of the drive as it is in the host. For example, if the disk size is 69 KB in the host, the VM will see the disk as 69 KB.
***

## Related Features
Does your suggestion relate to any existing features, or is it new?

Existing
***

## Concepts
If you can, please add some concept images.

![image](https://github.com/Coopydood/ultimate-macOS-KVM/assets/49075348/cf3f7eec-dce8-4a30-b96b-efeb052c59d7)

![image](https://github.com/Coopydood/ultimate-macOS-KVM/assets/49075348/a98cc67e-66a5-4958-b267-7b56aa9436ff)

***

## Additional Information
Add any other relevant information to your suggestion here.

N/A

**Comment by Coopydood** [comment]
This seems related to the "NVMe" selection. I assume it works okay when using a QEMU script? 

AFAIK libvirt doesn't have official NVMe drive type support yet hence the added QEMU args instead of a libvirt entry. Does changing the args to qcow2 fix your issue?

I'll close your other issue as it is combined with this one.

Look forward to hearing back, thanks.

**Comment by User8395** [comment]
Yes it does.

You can keep the cmdline argument, just change raw to qcow2.

**Comment by Coopydood** [comment]
Does macOS successfully install and boot with the virtual NVMe drive after this change?

**Comment by User8395** [comment]
Yes

**Comment by Coopydood** [comment]
Can you please post a screenshot here of macOS booted up and the NVMe in disk utility? Just about ready to implement the fix.

**Comment by User8395** [comment]
Can't rn. It's already installing.

**Comment by User8395** [comment]
https://tmpfiles.org/3535606/kooha-2023-12-21-17-07-34.mp4

**Comment by Coopydood** [comment]
Thanks, changes applied in dev branch awaiting release :)
