### ISSUE TITLE
[ULTMOS] Issues.md does not link to correct issue for the black screen for RX graphics cards

### ISSUE THREAD

**Issue by eversiege** [Coopydood/ultimate-macOS-KVM#46]
> [!NOTE]
> This should be used only to report a bug relating to the ULTMOS project itself, **not** macOS.

> [!IMPORTANT]
> To report an issue related to *AutoPilot* or any generated files, please use the dedicated AutoPilot issue template.

## Describe the Issue
Please describe your issue relating to **ultimate-macOS-KVM**.

https://github.com/Coopydood/ultimate-macOS-KVM/blob/main/docs/Issues.md#black-screen-or-reset-after-install-when-using-amd-rx-5xxx--6xxx-navi-gpus

The bold link does not redirect to correct issue.

**Comment by Coopydood** [comment]
https://github.com/Coopydood/ultimate-macOS-KVM/blob/main/docs/Issues.md#black-screen-or-reset-on-amd-rx-5xxx--6xxx-navi-gpus is the correct link.

**Comment by eversiege** [comment]
...why is it posted twice then
