### ISSUE TITLE
[macOS]

### ISSUE THREAD

**Issue by radiisys** [Coopydood/ultimate-macOS-KVM#51]
> [!NOTE]
> This should be used only to report a bug when running macOS **using ULTMOS**.

## Describe the Issue
Please describe your issue relating to **macOS** running under ULTMOS.
I cannot boot into any macOS installer nor finished environment. I just hang at EXITBS:START
***

## Steps to Reproduce
Describe how to accurately reproduce / exhibit the issue.
Go through setup, try to boot into macOS installer
***

## Expectation
What did you expect to happen instead?
Installer boots successfully
***

## Screenshots
If you can, please add some screenshots showing the issue.
![image](https://github.com/Coopydood/ultimate-macOS-KVM/assets/139723175/62357c8c-b606-41d3-9824-04ccccd216d8)

***

## System Information
Please enter your host system details to help contextualise the issue.

**OS:** [NixOS 24.05]
**Kernel:** [6.6.7-zen1]
**Processor:** [i5-8400]
**Memory:** [40GB]
**Graphics:** [Passed through RX580, and just using defaults with no passthrough]

***

## macOS
Please provide details of your macOS guest.

**Version:** [Big Sur -> Sonoma]

***

## ULTMOS
Please provide details of your ULTMOS repo setup.

**Version:** [v0.10.5]
**Branch:** [main]

***

## Additional Information
Add any other relevant information to your issue here.

**Comment by Coopydood** [comment]
Hi,

can you try with the v0.11.0 beta? You can get it on the dev branch. It includes some fixes that might help. 

Many thanks

**Comment by radiisys** [comment]
on it, thanks!

**Comment by radiisys** [comment]
boots perfect, thanks!

**Comment by Coopydood** [comment]
You’re very welcome! I’m just making some final tweaks to v0.11.0 and it’ll be released today :)

**Comment by radiisys** [comment]
found a secondary weird issue. after using your auto vfio passthrough stuff it seems to lose the ability to find the opencore image and i get booted to an efi shell

**Comment by Coopydood** [comment]
Yeah that’s happens to be one of the quick tweaks being made 😅

it’s a fairly easy workaround for now,
1. Type “exit”
2. Select “Boot Manager”
3. “Boot Options”
4. “Change boot order”
5. Move the EFI entry down under the QEMU HARDDISK entries 
6. Esc and “Continue”

**Comment by radiisys** [comment]
and now i can no longer boot if i use gpu passthrough! fix one issue, create a new one!

**Comment by Coopydood** [comment]
Are you using Sonoma?

**Comment by radiisys** [comment]
correct

**Comment by Coopydood** [comment]
Are you getting stuck somewhere around ``[PCI configuration begin]``?

**Comment by radiisys** [comment]
no, before that, i am unable to even get past opencore. hang on and ill enable logging to file

**Comment by Coopydood** [comment]
Are you able to join the discord? Would be a lot easier to help :)

**Comment by radiisys** [comment]
yeah sure, no worries

**Comment by radiisys** [comment]
joined, uname is rubiigen

**Comment by redmine4404** [comment]
same problem, i am on ULTMOS 0.11.1 and i'm stuck at LOG:EXITBS:START

**Comment by redmine4404** [comment]
i opened a new issue
