### ISSUE TITLE
[macOS] Unable to establish a USB connection between an iPhone physical device and Monterey

### ISSUE THREAD

**Issue by M3nti0nL3Ss** [Coopydood/ultimate-macOS-KVM#58]
### Describe the Issue

I am using Montery, on Arch Linux, and am experiencing difficulty connecting my iPhone via USB to Montery

### Operating System

Arch linux

### Kernel

6.7.0-arch3-1 (64-bit)

### Processor

i5-4570

### RAM (in GB)

20

### Version

v0.9.3

### Branch

main

**Comment by eversiege** [comment]
Hello! Thank you for trying out the project! I am seeing you’re using 0.9.3, which is really old. USB passthrough has been added in 0.11.0, so I would recommend you to update the script using the U button on the main menu, and then running USB Passthrough Assistant via the Extras Menu.

**Comment by M3nti0nL3Ss** [comment]
Thanks for the fast answer !
I just updated to the latest version, I added the necessary VFIO-PCI devices, and I got this error.
![image](https://github.com/Coopydood/ultimate-macOS-KVM/assets/30575106/abf68bf7-8cc9-41b5-87c6-105c945f28c4)

**Comment by M3nti0nL3Ss** [comment]
I added naviDetected = 0 under the gpuDetected and it worked

**Comment by Coopydood** [comment]
> I added naviDetected = 0 under the gpuDetected and it worked 

I'll get this fixed asap.

**Comment by M3nti0nL3Ss** [comment]
After running the new boot.sh file, QEMU won't even launch
![image](https://github.com/Coopydood/ultimate-macOS-KVM/assets/30575106/cbaa5b6b-275a-4df8-a153-2ee0f5633f4d)

**Comment by eversiege** [comment]
Seems like the porting issue because of updating from such old version. Can you try generating a new AutoPilot script? With the version you've just updated to, you can connect your .qcow file via AutoPilot with ease.

**Comment by Coopydood** [comment]
@M3nti0nL3Ss please see https://github.com/Coopydood/ultimate-macOS-KVM/pull/59#issuecomment-1906730686

**Comment by eversiege** [comment]
Hello, is this still an issue? I can close the issue or assist you further.

**Comment by M3nti0nL3Ss** [comment]
Thanks for the help, I finally got passthrough working. I used https://github.com/sickcodes/Docker-OSX#usbfluxd-iphone-usb---network-style-passthrough-osx-kvm-docker-osx to do it

**Comment by eversiege** [comment]
Reopening, waiting for @Coopydood, maybe this can be automated.
