### ISSUE TITLE
[ULTMOS] Issue with RHEL/CentOS/AlmaLinux/RockyLinux support. 

### ISSUE THREAD

**Issue by Hummenix** [Coopydood/ultimate-macOS-KVM#71]
### Describe the Issue

There are problems with running your scripts on RHEL. _(Note: I am using AlmaLinux, which should be binary compatible to RHEL)_
1. RHEL has no ``/usr/bin/qemu-system-x86_64``, the program providing this functionality resides in ``/usr/libexec/qemu-kvm`` instead. This can easily be fixed by the user by changing the line referring to the former in ``baseDomain`` to the latter.
2. RHEL does not support ``pc-q35-4.2``, or at least not under this name. I seem to be able to get around this by changing the machine type in the ``baseDomain`` config file to simply ``q35``.
```bash
error: Failed to define domain from boot.xml
error: unsupported configuration: Emulator '/usr/libexec/qemu-kvm' does not support machine type 'pc-q35-4.2'
```
_Note: At this point the script acts  as if it finished successfully, and then #70 appears._
```bash
[lain@seele ultimate-macOS-KVM]$ /usr/libexec/qemu-kvm -machine help
Supported machines are:
pc                   RHEL 7.6.0 PC (i440FX + PIIX, 1996) (alias of pc-i440fx-rhel7.6.0)
pc-i440fx-rhel7.6.0  RHEL 7.6.0 PC (i440FX + PIIX, 1996) (default) (deprecated)
q35                  RHEL-9.2.0 PC (Q35 + ICH9, 2009) (alias of pc-q35-rhel9.2.0)
pc-q35-rhel9.2.0     RHEL-9.2.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel9.0.0     RHEL-9.0.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel8.6.0     RHEL-8.6.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel8.5.0     RHEL-8.5.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel8.4.0     RHEL-8.4.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel8.3.0     RHEL-8.3.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel8.2.0     RHEL-8.2.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel8.1.0     RHEL-8.1.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel8.0.0     RHEL-8.0.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel7.6.0     RHEL-7.6.0 PC (Q35 + ICH9, 2009) (deprecated)
none                 empty machine
```
3. When the above is done we get to spice graphics, RHEL dropped support for those, I believe due to licensing issues with the h264 codec. Swapping this out for "vnc" in ``baseDomain`` yields a better result. 
_Note: At this point I do NOT get #70, however on my EndeavourOS (Arch) laptop I do._
4. After all of this we face an issue of qemu/kvm failing to start the device because "isa-applesmc" is not a supported device model: 
```bash
[lain@seele ultimate-macOS-KVM]$ sudo virsh start ultmos-12 
error: Failed to start domain 'ultmos-12'
error: internal error: QEMU unexpectedly closed the monitor (vm='ultmos-12'): 2024-02-17T23:38:21.856917Z qemu-kvm: -device isa-applesmc,osk=ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc: 'isa-applesmc' is not a valid device model name
```
My suspicion is that this last error has to do with RedHat removing support for Apple devices, also out of legal concerns and that this will not be fixable without a clean build of QEMU/KVM. I cannot confirm this because the sources I can find for the OS' version of the software don't seem to indicate this in any obvious manner, neither am I familiar enough with it to continue testing to find a work-around. 

_Note: My version of AlmaLinux is 9.3, which should be compatible only with RHEL 9(.3), some of this information does not apply to RHEL 8 and earlier, such as SPICE being unavailable._

_Sorry if this should have been a feature request instead, I wasn't quite sure about this, as you seemingly only test with Debian and Arch based distros, yet the "Minimum" requirements just name "linux-5.x"._ 

### Reproduce the Issue

Try to install any MacOS VM using this script on RHEL 9 (compatible distros) or newer. 

### Expectation

The VM would be created and running without a hitch. 

### Operating System

AlmaLinux 9.3 (Shamrock Pampas Cat) x86_64 

### Kernel

5.14.0-362.18.1.el9_3.x86_64 

### Processor

Intel Xeon E5-2683 v4 (64) @ 2.100GHz

### RAM (in GB)

~768

### Version

v0.11.0

### Branch

main

### Additional Information

I am skeptical of this being a fixable issue on your end, as I see the fault with RHEL's implementation of QEMU/KVM/libvirt, so you may just want to assign this to be a known issue and put a note in the README.

**Comment by Coopydood** [comment]
Thanks for your detailed report! I wouldn't mind learning a bit more about this- if you're able and willing to, could you join the discord?

Many thanks

**Comment by Hummenix** [comment]
@Coopydood willing, yes, but able, not so much. For whatever reason when I click the Discord button in the README (linking to https://sl.coopydood.com/discord) I just get to see a cloudflare page very nicely telling me about how the SSL handshake failed. 
<img width="510" alt="2024-02-18 23_22_54-sl coopydood com _ 525_ SSL handshake failed — Mozilla Firefox" src="https://github.com/Coopydood/ultimate-macOS-KVM/assets/36206434/48c0b554-a641-4c7d-948b-4af5ec72a184">
*Not a Firefox or extension problem either, tried Chrome and another computer as well, just to be sure. No luck anywhere.*

**Comment by Coopydood** [comment]
Yeah, my website is under maintenance... oops. 
https://discord.gg/WzWkSsT
