### ISSUE TITLE
[ULTMOS] cpuinfo usage with AMD Processor/Ubuntu

### ISSUE THREAD

**Issue by moulin-louis** [Coopydood/ultimate-macOS-KVM#81]
### Describe the Issue

During the step `Getting CPU information` running the `GRUB Argument Editor` through the `Extras` menu, the script crash during this snippet :
```
cpydLog("wait", "Getting CPU information...")
print("   Getting CPU information...")
try:
   import cpuinfo
   cpu_vendor = cpuinfo.get_cpu_info()['vendor_id_raw']
   cpu_model = cpuinfo.get_cpu_info()['brand_raw']
except:
   # If the user does not have py-cpuinfo installed, or if some other error occurs, the script will die, throwing the following error message.
   print("   I was unable to gather CPU information. Do you have py-cpuinfo installed?\n")
   cpydLog("fatal", "User either does not have py-cpuinfo installed, or hit CTRL-C.")
   exit()
```
py-cpuinfo is installed and with some strong debugging (some print statement), the error seem that the key `vendor_id_raw` and `brand_raw` doesn't exist. I've also notice that deleting the `_raw` suffix will fix the issue but I have no idea if this break something later.

### Reproduce the Issue

```
./main.py
`E`
`4`
````

### Expectation

Doesn't crash

### Operating System

Linux Ubuntu

### Kernel

6.5

### Processor

Amd Ryzen 5600X

### RAM (in GB)

16

### GPU(s)

Rtx 3080 + Amd RX 580

### Version

v0.11.2

### Branch

main

### Additional Information

Thanks for your help !

**Comment by Coopydood** [comment]
Thank you, we'll investigate this asap. 

Has everything else worked ok for you?

Thanks for using the project :)

**Comment by moulin-louis** [comment]
No worry ! Yes everything working fine for now ! I getting my AMD graphic card in few hours and will try gpu passtrough then. Thanks you for your work !

**Comment by moulin-louis** [comment]
That was my plan yes ! I've found some tiny error in the codebase that was easy to fix (some command substitution not working with fish my shel and some missing dependencies). I will try to make a pull request for this one early next week if we're allowed to contribute to this project.

**Comment by Hyperchromiac** [comment]
@moulin-louis, could you tell me what version of py-cpuinfo you have installed?

**Comment by moulin-louis** [comment]
Yes, I have py-cpuinfo version 5.0.0. Installed through apt but now I realized it must be really outdated.

**Comment by moulin-louis** [comment]
Just switch to py-cpuinfo 9.0.0 through pipx but that doesn't fix the issue, the script keep using version 5.0.0 after uninstalling the old apt version.
