### ISSUE TITLE
No such file or directory as python?

### ISSUE THREAD

**Issue by Hackintoshuser** [Coopydood/ultimate-macOS-KVM#82]
First time on debain 12 ryzen 7 3700u giving Traceback (most recent call last):
  File "/home/paul/ultimate-macOS-KVM/./main.py", line 345, in <module>
    subprocess.Popen(["python","./scripts/drpc.py","--os",macOSVer])
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
paul@debian:~/ultimate-macOS-KVM$

**Comment by Coopydood** [comment]
If you changed the code to `python3` does that change anything?

**Comment by Hackintoshuser** [comment]
> If you changed the code to `python3` does that change anything?

I just switched to arch and its working perfectly as a charm it seems to Debian has a problem with the python script i wouldn't know what happened cause im kinda new to linux

**Comment by Coopydood** [comment]
Okay thank you for bringing this to my attention anyway- I hope you enjoy the project and find it useful. Feel free to ask if you need any more help or just want to provide feedback :) 

You can get quicker replies on discord: https://discord.gg/WzWkSsT
