### ISSUE TITLE
[SUGGESTION] Leverage existing OSx boot drive (Hackintosh) to create VM

### ISSUE THREAD

**Issue by tlvenn** [Coopydood/ultimate-macOS-KVM#83]
### Describe the Suggestion

Maybe a little niche but might be simple to do, i am not knowledgeable enough in this area to answer this...
 I am on an hackintosh triple booting osx / win11 / nixos with my main driver being nixos. I was able to create a vm to boot my existing win11 drive seamlessly but I have no idea how to do the same with OSx.

Is it something that this project could help with ?

### Suggestion Type

- [ ] New Feature
- [x] Related to an existing feature
- [ ] Other

**Comment by Coopydood** [comment]
I actually do the same on my system. It's fairly easy- when using the project's AutoPilot script, you can switch to a physical disk when configuring the hard disk. 

You should also use the OpenCore assistant (found in the Extras menu) to mount and open the config so you can change the serial number and SMBIOS to match your main hackintosh. 

If you need anything else feel free to ask or join the discord. :)

**Comment by tlvenn** [comment]
Hi @Coopydood, thanks for getting back to me, I could definitely use some help, tried to join your discord server but your link is dead (https://sl.coopydood.com/discord).

**Comment by Coopydood** [comment]
Try https://discord.gg/WzWkSsT
