### ISSUE TITLE
[macOS] - can't regain control of host after passthrough shutdown

### ISSUE THREAD

**Issue by omarz-vst** [Coopydood/ultimate-macOS-KVM#84]
### Describe the Issue

I'm using the latest version of ulitmate-macos-kvm with sonoma and single gpu passthrough.
Everything works as expected, the only issue I'm facing is when I shutdown the guest which has gpu passthrough, the guest shuts down and I can get back to the host screen.

I can move the mouse cursor, but can't click or use the keyboard buttons, the only solution is to reboot the guest from the reset switch.

### Operating System

Arch

### Kernel

linux 6.8.6

### Processor

i7-8700

### RAM (in GB)

32

### GPU(s)

rx580

### Version

0.11.2

### Branch

main

**Comment by eversiege** [comment]
Sounds like a sleep/wake issue. [Can you try following these steps on OpenCore website?](https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html)

**Comment by gleidhold** [comment]
I am not sure what method you are using for passthrough (it happens to me with single GPU passthrough), but maybe check the name in the hooks file is exactly the same as your VM.
