### ISSUE TITLE
[SUGGESTION] Add agdpmod=pikera to boot args in config.plist

### ISSUE THREAD

**Issue by BurritoSuicide** [Coopydood/ultimate-macOS-KVM#91]
### Describe the Suggestion

Would be awesome to expand this script to include the mentioned boot flag prior in the config.plist for people planning to passthrough an AMD GPU that requires this. I successfully got single-gpu passthrough using your script and think this would be a great addition. Also, consider adding other boot args based on lscpu/pci settings grabbed from the script (if it detects radeon graphics, ask to include those args, nvidia other boot args). These are from the dortiana guide https://dortania.github.io/GPU-Buyers-Guide/misc/bootflag.html#amd-boot-arguments.

### Suggestion Type

- [X] New Feature
- [ ] Related to an existing feature
- [ ] Other

**Comment by Coopydood** [comment]
Hi, this is already part of the VFIO Passthrough assistant! Upon detecting a Navi GPU, the boot patch is offered to the user. 

Boot patches are also available in **Main menu > macOS Boot Argument Editor > AutoPatch**. 

Take care

**Comment by BurritoSuicide** [comment]
Oh, nice! I guess I just didn't notice/pick it up haha. Thanks man, appreciate the clarity.
