### ISSUE TITLE
[macOS] stuck on Base System

### ISSUE THREAD

**Issue by rashadgasimli** [Coopydood/ultimate-macOS-KVM#93]
### Describe the Issue

Hello, I installed macOS Ventura with AutoPilot, but when I start "macOS Base System" for configuring, it stucks on the log screen even while 15+ minutes.

![Screenshot from 2024-06-05 00-43-58](https://github.com/Coopydood/ultimate-macOS-KVM/assets/158089693/42642da3-0133-499b-ad67-0e3fa060ecc1)

### Operating System

Fedora Linux 40 (Workstation Edition) x86_64

### Kernel

Linux 6.8.11-300.fc40.x86_64

### Processor

11th Gen Intel(R) Core(TM) i5-11400H (12) @ 4.50 GHz

### RAM (in GB)

16 GB (15.36 GiB)

### GPU(s)

GPU 1: Intel UHD Graphics @ 1.45 GHz [Integrated]  | GPU 2: NVIDIA GeForce RTX 3050 Mobile [Discrete]

### Version

v0.11.3

### Branch

main

**Comment by RashadGasimli** [comment]
Can't drop any logs or script files, beacuse I'm using firefox flatpak version under wayland. So it's impossible to drag or drop files

**Comment by TheUndscr** [comment]
having the same issue, i use Fedora 40 x86_64, and I have an AMD Ryzen 5 4600H CPU, as well as an NVIDIA 1650 dedicated gpu. Attempting to use Ventura with autopilot, as well

**Comment by Coopydood** [comment]
> having the same issue: i use Fedora 40 x86_64, and I have an AMD Ryzen 5 4600H CPU, as well as an NVIDIA 1650 dedicated gpu. Attempting to use Ventura with autopilot, as well

Based on some stuff tried by @TheUndscr on discord, perhaps try setting the CPU threads to 1 and see if it boots then. Obviously that doesn’t exactly do wonders for hyperthreading but it might let you boot and investigate further. 

You should also try the dev version if you haven’t already, as it contains some misc fixes 
```./scripts/repo-update.py --force --targetBranch dev```
(And re run autopilot)

if you’d like quicker / more interactive help then please feel free to join the discord. 

Many thanks

**Comment by leqord** [comment]
Same here on Opensuse Tumbleweed

**Comment by zt64** [comment]
Also having this bug on Arch Linux
I did some testing trying a few things. Switching to dev branch didn't fix, nor did setting threads to 1 work. 

What did work was when I set the set the macOS version to High Sierra then it boots and goes to the utilities

Might be relevant that my graphics card is Nvidia RTX 3070 running 555.58.02 drivers

**Comment by eversiege** [comment]
Is this bug still reproducible? This issue needs more info, otherwise it will be closed @leqord @zt64 @TheUndscr @rashadgasimli

**Comment by rashadgasimli** [comment]
> Is this bug still reproducible? This issue needs more info, otherwise it will be closed @leqord @zt64 @TheUndscr @rashadgasimli

I fixed by setting cpu cores to 6, anyway thanks for support.
