### ISSUE TITLE
[SUGGESTION]  is there support for osx hosts? thx

### ISSUE THREAD

**Issue by kocoman2** [Coopydood/ultimate-macOS-KVM#99]
### Describe the Suggestion

 is there support for osx hosts? thx

### Suggestion Type

- [ ] New Feature
- [ ] Related to an existing feature
- [ ] Other

**Comment by Coopydood** [comment]
TLDR: Not officially, no. 

It's possible and for the sake of testing _I have done it before_, but it's pretty pointless as you can't pass the GPU through or anything advanced. 

VMware Fusion or Parallels is likely the best option on OS X. 

If you insist on using it on macOS for the sake of being a nerd, then you can bypass the OS check by running
```
./main.py --skip-os-check
```
